# Generated by Django 5.1.1 on 2024-10-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='Earth', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='short_intro',
            field=models.CharField(blank=True, default='This is a default bio. User has not added a bio yet.', max_length=200, null=True),
        ),
    ]
